# -*- coding: utf-8 -*-
"""C223.Chirag.Devgade.2nd.year.SM.Lab-6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QrYb-vr3I5xKDLacZfRcsMx3aFF58GvX
"""

import pandas as pd
import numpy as np

file = pd.read_csv('churn-bigml-20.csv')
print(file)

# min and max
file['Account length'].min(), file['Account length'].max()

# summary/statiscal data of all data
file.describe(include='all')

# all columns from this dataset
print(file.columns)

# number of unique data elements in each columns
file.nunique()

# all unique elements column wise
print('State: ', file['State'].unique(), '\n')
print('Account length: ', file['Account length'].unique(), '\n')
print('Area code: ', file['Area code'].unique(), '\n')
print('Churn: ', file['Churn'].unique(), '\n')
print('Customer service calls: ', file['Customer service calls'].unique(), '\n')

# information about invdividual columns
file.info()

# histograms
file['Total day minutes'].hist()

# histograms
file['Total intl calls'].hist()

# barplot
import seaborn as sns

sns.barplot(file['Total day calls'], file['Total eve calls'])

# heatmap with annotation on
sns.heatmap(file.corr(), annot=True)

# heatmap with annotation off
sns.heatmap(file.corr(), annot=False)

# pairplot from sns
data = pd.DataFrame(file)
sns.pairplot(data)

# boxplot
import matplotlib.pyplot as plt

sns.catplot(x="Total eve minutes", y="Total day minutes", data=data, kind="box")
plt.title("Boxplot for Total eve minutes and Total day minutes")
plt.show()

# Ordinal encoding
import pandas as pd

pd.get_dummies(file['Total eve minutes'].head(5))

# label encoder
from sklearn import preprocessing

l_enc = preprocessing.LabelEncoder()
l_enc.fit(['LA', 'NY', 'HI', 'AL', 'VT'])
l_enc.transform(['HI', 'AL', 'VT'])
